import calculator  #importing the whole calculator module
# from calculator import add, subtract #import specific functions from calculator module
from calculator import *   #import all the functions from calculator module

import config  #importing the whole config module
from student import Student #importing the Student class from student module

import math #importing the math module which is a built-in module in python
import random #importing the random module which is a built-in module in python
import guessNumber #importing the guessNumber module which is a user-defined module in the same directory as main.py
from datetime import datetime  #importing the datetime module which is a built-in module in python
import os
import sys
# ------------------- importing from ---------calculator--------------------
sum = calculator.add(12,6)
print(f"sum = {sum}")

sum = calculator.substraction(12,6)
print(f"substraction = {sum}")

sum = calculator.sumEven(10)
print(f"sum of even numbers = {sum}")

# --------------------  import the config file --------------------
print(config.APP_NAME)
print(config.VERSION)


# -------------------- import the student class from student module --------------------
student1 = Student("Lisa Emesowum")
student1.display() # this will print the name of the student which is "Lisa Emesowum"

# -------------------- import the math module --------------------
print(math.sqrt(16)) # this will print the square root of 16 which is



# different between ceil and floor
# ceil will round up the number to the nearest integer while floor will round down the number to the nearest integer
print(math.ceil(4.2)) # this will print 5 which is the smallest integer greater than or equal to 4.2

# floor will round down the number to the nearest integer while ceil will round up the number to the nearest integer
print(math.floor(4.2)) # this will print 4 which is the largest integer less than or equal to 4.2



# -------------------- import the random module --------------------
print(random.randint(1, 10)) # this will print a random integer between 1 and 10

# write guess the number in my mind and then try again and again until you guess the number correctly
number = random.randint(1, 10)
# get the number from the user and to see if the number is correct or not if the user guess the number correctly print "Congratulations! You guessed the number correctly!" and if the user guess the number incorrectly print "Sorry! You guessed the number incorrectly. The number was {number}" where {number} is the number that was generated by the random module
# and press the 0 to exit the game
number = guessNumber.generate_number()

while True:
    input_number = int(input("Guess the number between 1 and 10 (0 to exit): "))

    result = guessNumber.check_guess(input_number, number)

    if result == "correct":
        print("WOW! CONGRATULATIONS FOR GUESSING THE NUMBER CORRECTLY")
        break

    elif result == "exit":
        print("Game exited. Bye!")
        break

    else:
        print("OOp, Sorry try again later thank you")
        
# date and time
print(datetime.now()) #date and time
# os
print(os.getcwd()) #
# system
print(sys.version) #location of the project 
# 
# if __name__ == "__name__":
#     print(add(45,60))
    