# write a program to  guess the number in my mind and then try again and again until you guess the number correctly
# get the number from the user and to see if the number is correct or not if the user guess the number correctly print "Congratulations! You guessed the number correctly!"
# and if the user guess the number incorrectly print "Sorry! You guessed the number incorrectly. The number was {number}" where {number} is the number that was generated by the random module
# and press the 0 to exit the game
import random

number = 5 #the lucky number

while True:
    input_number = int(input("Hello guys,Guess the number in my mind between 1 and 10: "))
    if input_number == number:
        print("WOW!, CONGRATULATION FOR GUESS MY LUCKY NUMBER CORRECTLY")
        break
    # if input_number == 0:
    #     print("OOp, Sorry try again later thank you,")
    #     break
    else:
        print("OOp, Sorry try again later thank you,")
    input_number = int(input("Guess the number in my mind between 1 and 10: "))
    break
    # to exit
    
   
#   ANOTHER METHOD
def play_game(number):
    return random.randint(1,10)

def guest(user_guess,number):
    if user_guess == number:
        print("WOW!, CONGRATULATION FOR GUESS MY LUCKY NUMBER CORRECTLY")
    elif user_guess == 0:
        print("OOp, Sorry try again later thank you,")    
    else:
        print(f"OOp, Sorry try again later thank you, the number was {number}")
     
     
def generate_number():
    return random.randint(1, 10)


def check_guess(user_input, number):
    if user_input == number:
        return "correct"
    elif user_input == 0:
        return "exit"
    else:
        return "wrong"
    

